services:
  chatapp:
    image: chatapp:latest
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
