"""update restaurants model

Revision ID: 6469d121b85d
Revises: be4ae59a00be
Create Date: 2025-04-16 20:34:27.023600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6469d121b85d'
down_revision: Union[str, None] = 'be4ae59a00be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('five_stars', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('four_stars', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('three_stars', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('two_stars', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('one_stars', sa.Integer(), nullable=True))
    op.add_column('restaurants', sa.Column('total_review_counts', sa.Integer(), nullable=True))
    op.alter_column('restaurants', 'overall_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('restaurants', 'food_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('restaurants', 'service_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('restaurants', 'ambience_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'ambience_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('restaurants', 'service_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('restaurants', 'food_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('restaurants', 'overall_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('restaurants', 'total_review_counts')
    op.drop_column('restaurants', 'one_stars')
    op.drop_column('restaurants', 'two_stars')
    op.drop_column('restaurants', 'three_stars')
    op.drop_column('restaurants', 'four_stars')
    op.drop_column('restaurants', 'five_stars')
    # ### end Alembic commands ###
